export {default as Details} from './Details';
export {default as Desc} from './Desc';
export {default as Gallery}from './Gallery';
export {default as Rating} from './Rating';
export {default as StyleSelect} from './StyleSelect';
export {default as Product} from './Product';
export {default as Navbar} from './Navbar';
export {default as Banner} from './Banner';
export {default as ButtonGroup} from './ButtonGroup';
export {default as Sharing} from './Sharing';